<?php

namespace FilmyBundle\Entity;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * ActorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseUser
{
	
}
