<?php

namespace Proxies\__CG__\FilmyBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orders extends \FilmyBundle\Entity\Orders implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'id', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'status', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'term', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'form', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'conditions', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'idFilm', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'idClient');
        }

        return array('__isInitialized__', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'id', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'status', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'term', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'form', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'conditions', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'idFilm', '' . "\0" . 'FilmyBundle\\Entity\\Orders' . "\0" . 'idClient');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orders $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerm($term)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerm', array($term));

        return parent::setTerm($term);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerm', array());

        return parent::getTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function setForm($form)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForm', array($form));

        return parent::setForm($form);
    }

    /**
     * {@inheritDoc}
     */
    public function getForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForm', array());

        return parent::getForm();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditions($conditions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditions', array($conditions));

        return parent::setConditions($conditions);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditions', array());

        return parent::getConditions();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFilm($idFilm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFilm', array($idFilm));

        return parent::setIdFilm($idFilm);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFilm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFilm', array());

        return parent::getIdFilm();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdClient($idClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdClient', array($idClient));

        return parent::setIdClient($idClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdClient', array());

        return parent::getIdClient();
    }

}
