FilmyBundle\Entity\Review:
    type: entity
    table: null
    repositoryClass: FilmyBundle\Entity\ReviewRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idFilm:
            type: integer
            column: Id_film
        title:
            type: string
            length: 255
            column: Title
        text:
            type: string
            length: 255
            column: Text
    lifecycleCallbacks: {  }
