filmy_homepage:
    path:     /
    defaults: { _controller: FilmyBundle:Default:index }
filmy_helloworld:
    path:     /hello
    defaults: { _controller: FilmyBundle:Default:helloworld }
filmy_gladiator:
    path:	/Movies/gladiator
    defaults: { _controller: FilmyBundle:Default:Gladiator }
filmy_commedy:
    path:	/Types/commedy
    defaults: { _controller: FilmyBundle:Default:Commedy }