filmy_homepage:
    path:     /
    defaults: { _controller: FilmyBundle:Default:index }
filmy_moviesdisplay:
    path:	/Movie/{id}
    defaults: { _controller: FilmyBundle:Default:MoviesDisplay }
filmy_review:
    path:   /Review
    defaults: { _controller: FilmyBundle:Default:Review }
filmy_movies:
    path:   /Movies
    defaults: { _controller: FilmyBundle:Default:Movies }
filmy_actors:
    path:   /Actors
    defaults: { _controller: FilmyBundle:Default:Actors }
filmy_orders:
    path:   /Orders
    defaults: { _controller: FilmyBundle:Default:Orders }
filmy_actorsview:
    path:   /ActorsView
    defaults: { _controller: FilmyBundle:Default:ActorsView }
filmy_reviewsdisplay:
    path:   /ReviewDisplay
    defaults: { _controller: FilmyBundle:Default:ReviewsDisplay }
filmy_orderslist:
    path:   /OrdersList
    defaults: { _controller: FilmyBundle:Default:OrdersList }
filmy_ordersbuy:
    path:   /OrdersBuy
    defaults: { _controller: FilmyBundle:Default:OrdersBuy }