filmy_homepage:
    path:     /
    defaults: { _controller: FilmyBundle:Default:index }
filmy_helloworld:
    path:     /hello
    defaults: { _controller: FilmyBundle:Default:helloworld }
filmy_moviesdisplay:
    path:	/Movies/{moviesdisplay}
    defaults: { _controller: FilmyBundle:Default:Movies }
filmy_commedy:
    path:	/Types/commedy
    defaults: { _controller: FilmyBundle:Default:Commedy }
filmy_review:
    path:   /Review
    defaults: { _controller: FilmyBundle:Default:Review }
filmy_movies:
    path:   /Movies
    defaults: { _controller: FilmyBundle:Default:Movies }
filmy_actors:
    path:   /Actors
    defaults: { _controller: FilmyBundle:Default:Actors }
filmy_orders:
    path:   /Orders
    defaults: { _controller: FilmyBundle:Default:Orders }
filmy_moviesview:
    path:   /MoviesView
    defaults: { _controller: FilmyBundle:Default:MoviesView }
filmy_actorsview:
    path:   /ActorsView
    defaults: { _controller: FilmyBundle:Default:ActorsView }
filmy_query:
    path:   /Query
    defaults: { _controller: FilmyBundle:Default:Query }